### ISSUE TITLE
Raw Request Bug [304 Response = i/o timeout]

### ISSUE THREAD

**Issue by Impact-I** [projectdiscovery/rawhttp#98]
Sorry, but the example with nuclei is easier for me

### Nuclei version:
[INF] Current Version: 2.8.9

### Current Behavior:
When sending an unprocessed request with a 'If-Modified-sinCe' header, no response is received and the request goes into a long timeout.

### Expected Behavior:
An raw request must receive a valid response.

### Steps To Reproduce:
**Template:**
```yaml
id: C
info:
  name: C
  author: C
  description: C
 
requests:
  - raw:
      - |+
        GET /service-worker.js HTTP/1.1
        Host: rutube.ru
        If-Modified-Since: Tue, 21 Feb 2023 14:51:35 GMT

    unsafe: true
```
**Command:**
```bash
./nuclei -debug -t temple.yaml -u https://rutube.ru
```

2. Notice that instead of response
```http
HTTP/1.1 304 Not Modified
Connection: close
Cache-Control: max-age=0
Date: Sat, 25 Feb 2023 17:42:57 GMT
Last-Modified: Tue, 21 Feb 2023 14:51:35 GMT
Server: QRATOR
Set-Cookie: uuid=94823265-14f0-d067-34b0-180e;
```

we get exception  could not read http body: read tcp  `192.168.1.1:8080->198.248.233.148:443: i/o timeout`

You can remove unsafe: true from the yaml file to see the correct response.
OS: Windows 10, Ubuntu 18.04
